dubbo:
  application:
    name: service-goods
  registry:
    address: zookeeper://192.168.159.129:2181
  protocol:
    port: -1
  consumer:
    check: false
spring:
  datasource:
    url: jdbc:mysql:///shop1909?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 192.168.159.129
    username: admin
    password: admin
    virtual-host: /admin
    port: 5672
  redis:
    host: 192.168.159.129
mybatis-plus:
  mapper-locations: classpath:com/qf/dao/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl